// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skwela.Infrastructure.Data;

#nullable disable

namespace Skwela.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260301065358_AddedEmailVerifyFlag")]
    partial class AddedEmailVerifyFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skwela.Domain.Entities.Classroom", b =>
                {
                    b.Property<Guid>("class_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("class_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("class_description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("class_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.HasKey("class_id");

                    b.HasIndex("class_id");

                    b.HasIndex("user_id");

                    b.ToTable("Classrooms");
                });

            modelBuilder.Entity("Skwela.Domain.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("user_id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("class_id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("enrolled_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("enrolled_status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("user_id");

                    b.HasIndex("class_id");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("Skwela.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("user_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("display_image")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("display_name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("is_email_verified")
                        .HasColumnType("boolean");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("refreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime>("refreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("role")
                        .HasColumnType("integer");

                    b.Property<DateTime>("user_created_at")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("user_id");

                    b.HasIndex("role");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Skwela.Domain.Entities.Classroom", b =>
                {
                    b.HasOne("Skwela.Domain.Entities.User", "user")
                        .WithMany("classrooms")
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Skwela.Domain.Entities.Enrollment", b =>
                {
                    b.HasOne("Skwela.Domain.Entities.Classroom", "classroom")
                        .WithMany()
                        .HasForeignKey("class_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Skwela.Domain.Entities.User", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("classroom");

                    b.Navigation("user");
                });

            modelBuilder.Entity("Skwela.Domain.Entities.User", b =>
                {
                    b.Navigation("classrooms");
                });
#pragma warning restore 612, 618
        }
    }
}
